### PR TITLE
Fix synopsis formatting errors and neat-ify it

### PR DESCRIPTION
**Pull request by eshrh**
eshanmind back at it again!

When looking at anime synopsis, 3 errors become glaringly obvious

+ a nasty `<br />\r\n<br />\r\n` code is inserted every time there is a line break.
+ some characters like `—` and `'` get replaced with their html codes, `&mdash;`, and `&#039`
+ At the end of every synopsis there is sometimes a `[Written by MAL Rewrite]` or `(Source: ANN)` or something of the sort. This is perhaps a personal thing, but it would be cleaner if it wasn't there. 

_Bob the builder can we fix it?_
**I fixed it**

<sup>PS: please disregard the fact that the head branch is "sysopsis" instead of "synopsis" I just realized it along with the fact that i might be mentally handicapped</sup>

tuturuuu
~eshanmind

### CODE REVIEW

**Comment by Utagai** [comment]
Looks good to me. Ready for merge?

**Comment by eshrh** [comment]
I'd like to refactor it a little to make it scalable if other things need to be deleted in the future. In addition I want to remove bbcode tags, should be ready for merge in max 12 hours

**Comment by Utagai** [comment]
Great. Let me know. Thanks again.

**Comment by eshrh** [comment]
@Utagai ready for merge now, tested, works properly

**Pull request merged**
