### PR TITLE
Make Medium_List iterable

### PR DESCRIPTION
**Pull request by eshrh**
Small change to make medium_list an iterable class, I couldn't figure out a way to lazily return the next object, so I converted medium_list dictionary into a list and returned the iterator of that list.

To be at least a little considerate of the user's time, I wrote it so that if the user didn't actually want to iterate over the list, it doesn't actually do the calculations( also, it doesn't repeat the calculation if `__iter__()` is called twice).

Solves #32!

### CODE REVIEW

**Comment by eshrh** [comment]
I think travis stuff is failing since you pushed travis out before I forked/pulled this to my branch.

**Comment by Utagai** [comment]
@eshanmind You may be right. Have you tried just rebasing your branch on top of master (which has what should be required from the `travis` branch)?

**Comment by eshrh** [comment]
@Utagai fixed!

Edit: nevermind

**Comment by eshrh** [comment]
I'm not going to lie, I can't figure this out. For now, since this is a really small PR, i'm just going to hard reset my fork and make a new PR.

**Pull request closed without merging**
