### PR TITLE
New Documentation YAY!!!!

### PR DESCRIPTION
**Pull request by eshrh**
Hey There!

I'd love to be a part of this project, and to familiarize myself with how the code works and all that stuff, i decided to renovate the lackluster "how do you use it" with some strong, hearty, and crystal clear "Documentation"! I also found a few places that need improvement like:
-#24
- compatibility should also take into account the genres liked by both users, not just how high they rated the same anime (workin on this one atm)

~~I literally love you for making this I'm so done with the official MAL api ugh.~~
~eshanmind

### CODE REVIEW

**Comment by Utagai** [comment]
This is a lot of work that many would consider boring or soul-draining, but you've taken it on -- for that, I'm super appreciative. You are of course welcome to work on this project. I didn't expect anyone to even find this (although I did post about it on the MAL forums in case anyone would want to use it), so the fact that I have some people coming and going to help here and there is already more than I can ask for. I'm perpetually busy with school or work, so it's very helpful to me.

**Comment by eshrh** [comment]
quick thing, line 109 no closing bracket

**Comment by Utagai** [comment]
Ready to merge @eshanmind? 
Looks good to me as far as I can tell.

**Comment by eshrh** [comment]
Yes @Utagai

**Pull request merged**
