### PR TITLE
PEP8, removed __future__ import; (redundant as of py3), Removed usele…

### PR DESCRIPTION
**Pull request by byronvanstien**
…ss docstrings; changed to Python conventions for variable declaration. Changed comments to actual comments rather than wannabe docstrings. Removed unused imports.

### CODE REVIEW

**Comment by byronvanstien** [comment]
There are some things I missed out of the .gitignore; you may want to add those back in. (I also recommend reading some python style guides. You've done things weirdly in all aspects tbh)

**Comment by Utagai** [comment]
I'm not surprised that I've broken some Python stylistic rulings when it comes to documentations/comments (and from your changes, also spacings in between variable defines/declares and their values). I come from a _heavy_ C background, with an education rooted in Java, so perhaps I'm just too new!

Since these are choices of style that do not modify any of the API's functionality, I think it's more beneficial if I try making these changes myself when I have the time -- that way I can learn and maintain the API (...when I actually have time to do anything but work, of course) while adhering to the right rules. 

Thank you for your contribution, this has shed a lot of light on what I need to improve in my Python coding.

I'll definitely be incorporating all of your changes in due time, but I will not be merging this pull request to do so.

Thanks! Let me know what you think. I always appreciate this kind of constructive criticism! Because I would like to offer chance for discussion, I won't be closing this.

**Comment by byronvanstien** [comment]
May I also suggest using classes with methods over functions; this helps out for the API with a Client class, where you could pass the username and password in and use the same auth for every method (although this isn't strictly needed). This is under the assumption the API is used where there is an endpoint for what is needed. This would also allow for some abstraction, like putting flags underneath an object.

**Comment by Utagai** [comment]
Going to revive this discussion for a tiny bit as I find myself with time to actually look back on this project. Your changes to `setup.py` don't make sense to me w.r.t. PEP8, actually, those changes seem to violate  PEP8. Unless there is some special ruling on variable declaration spacing in Python for a `setup.py` file I don't think this is correct.

I also noticed that you removed docstring module-level strings, in things like `constants.py`. You removed the overarching description of the module files. However, there is nothing wrong with a module level docstring, as a matter of fact, [PEP257](https://www.python.org/dev/peps/pep-0257/) specifies this:
> All modules should normally have docstrings, and all functions and classes exported by a module should also have docstrings. 

Furthermore,  and this is seen mostly in constants.py, I added docstrings before variables at the global scope. These were removed, but PEP257 also references these as a kind of docstring: _attribute docstrings_:
> String literals occurring immediately after a simple assignment at the top level of a module, class, or __init__ method are called "attribute docstrings". 
These strings are not specially handled by Python, and are just processed and then left to the dust, but they do have purpose and are often considered good practice to have -- and in a future where I may use a documentation generator,  they may even come in handy (see next paragraph).

Actually, some major python documentation generators/parsers accept and look for docstrings occuring near variables like in `constant.py` (think Sphinx, Epydoc). The change I will need to make however, is the ordering of the docstrings. In C/Java, you put them above the variable, but in Python it fits the style to go _after_, as well as splitting up doc strings that refer to two variables at once into a single one each.


Any other changes I didn't mention have been applied (not through the pull request though, but they are now in the codebase). Thanks again! I'm sure I still don't know a lot but I hope to get better over time and make less and less mistakes. Sorry for the huge delay, but I simply have more important things to spend time on (school, work, loved ones, etc) than this. Hopefully I can give it some more love now in the comming weeks. :smile:

**Pull request closed without merging**
